export const  traitsData=[
    "honest",
    "cheerful",
    "kind",
    "self-confident",
    "optimistic",
    "grateful",
    "thoughtful",
    "shy",
    "humorous",
    "generous",
    "curious",
    "caring",
    "likeable",
    "loyal",
    "quiet",
    "serious",
    "fun",
    "calm",
    "moody",
  ]

  export const interestsData=[
    "Traveling",
    "Football",
    "Watching TV",
    "Baseball",
    "Music",
    "Cars",
    "Basketball",
    "Cooking",
    "Pets",
    "Working out",
    "Computer games",
    "Dancing",
    "Arts",
    "Gardening",
    "Fishing",
    "Hunting",
    "Hockey",
    "Reading",
    "Boxing",
    "Fashion",
    "Nature",
    "Soccer",
    "Biking",
    "Tennis",
    "Astrology",
    "Golf",
    "Photography",
    "Fitness",
    "Yoga",
    "Volunteering",
    "Shopping",
    "Other",
  ]

  export const moviesData=[
    "Documentary",
    "Animation",
    "Comedy",
    "Adventure",
    "Horror",
    "Action",
    "Thriller",
    "Drama",
    "Romcom",
    "Western",
    "Science fiction",
    "Crime film",
    "Historical drama",
    "Fantasy",
    "Don't like movies",
  ]

  export const musicData=[
    "Rock",
    "Pop",
    "Electronic",
    "Classical music",
    "Jazz",
    "Hip-hop",
    "Melomaniac",
    "Country",
    "Folk",
    "Don't like music",
  ]

  export const lookingForData=[
    "chatting",
    "finding a friend",
    "having fun",
    "get attention",
    "i am bored",
    "other",
  ]